# Generated by Django 4.0.3 on 2023-01-18 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='found_cache_images',
        ),
        migrations.AddField(
            model_name='foundcacheimage',
            name='game_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='found_cache', to='game.gameresult'),
            preserve_default=False,
        ),
    ]
