# Generated by Django 4.0.3 on 2023-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_picture_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='hint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
