# Generated by Django 4.0.3 on 2023-01-20 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gameresult_found_cache_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='radius',
        ),
        migrations.AddField(
            model_name='game',
            name='zoom',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
